version: 2.1

parameters:
  environment:
    type: enum
    enum: ["staging", "production"]
    default: "staging"

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Display Branch Name
          command: |
            echo "Building on branch: $CIRCLE_BRANCH"
      - run:
          name: Install Dependencies
          command: |
            echo "Installing dependencies..."
            # Example: yarn install or npm install
      - run:
          name: Run Unit Tests
          command: |
            echo "Running unit tests..."
            # Example: yarn test or npm test
      - run:
          name: Conditional Step Example
          command: |
            if [ "$CIRCLE_BRANCH" == "main" ]; then
              echo "This is the main branch, performing additional actions."
            else
              echo "Not the main branch, skipping additional actions."
            fi

  deploy:
    docker:
      - image: cimg/base:stable
    parameters:
      environment:
        type: enum
        enum: ["staging", "production"]
    steps:
      - run:
          name: Deploy Job
          command: |
            echo "Deploying to << parameters.environment >> environment"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: workshop/circleci
          environment: "production"
