version: 2.1

parameters:
  environment:
    type: string
    default: "staging"

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run: |
          if [ "pipeline.parameters.environment" == "staging" ]; then
            echo "Building in << pipeline.parameters.environment >> environment"
          else
            echo "No Build allowed"
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: "Run Tests"
          command: |
            echo "Running on branch: $CIRCLE_BRANCH"
            pytest tests/